[project]
name = "ibs-cbs-copilot"
version = "0.1.0"
description = ""
authors = [
    {name = "Nelson Dell",email = "juniordell123@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "llama-index (>=0.14.23,<0.15.0)",
    "openai (>=2.46.0,<3.0.0)",
    "psycopg[binary] (>=3.3.4,<4.0.0)",
    "pgvector (>=0.5.0,<0.6.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "pymupdf (>=1.28.0,<2.0.0)",
    "tiktoken (>=0.13.0,<0.14.0)"
]
[tool.pytest.ini_options]
pythonpath = ["."]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
